services:
  - type: web_service
    name: amritsari-kulcha-system
    runtime: node
    repo: https://github.com/Yash282802/amritsari-kulcha-system
    branch: main
    plan: free
    region: singapore
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/catalog/menu
    envVars:
      - key: DATABASE_URL
        sync: false
